apiVersion: v1
data:
  PUBLIC_REPOS: https://charts.bitnami.com/bitnami,https://prometheus-community.github.io/helm-charts,https://repos.emqx.io/charts,https://nats-io.github.io/k8s/helm/charts,https://chartmuseum.github.io/charts
kind: ConfigMap
metadata:
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: argocd-complementary-operator
    app.kubernetes.io/managed-by: kustomize
  name: public-repos
